# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# Libraries
import pandas as pd
import numpy as np

# Challenge 1 - Index Functions

In this challenge, we will practice the advanced functions introduced in the lesson. However, before we start, we will load and evaluate our dataset. 

Load the dataset from Ironhack's database:
* db: `admissions predict`
* table: `admissions predict`

In [10]:
# your code here
data=pd.read_csv("Admission_Predict.csv")
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

Remove trailing spaces at the end of the column names if there are any.

In [3]:
# your code here
data.head()
#removing trailing and leading spaces in the columns names
data.columns = data.columns.str.strip()

Let's evaluate the dataset by looking at the `head` function.

In [4]:
# your code here
data.head(20)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65
5,6,330,115,5,4.5,3.0,9.34,1,0.90
6,7,321,109,3,3.0,4.0,8.20,1,0.75
7,8,308,101,2,3.0,4.0,7.90,0,0.68
8,9,302,102,1,2.0,1.5,8.00,0,0.50
9,10,323,108,3,3.5,3.0,8.60,0,0.45
10,11,325,106,3,3.5,4.0,8.40,1,0.52
11,12,327,111,4,4.0,4.5,9.00,1,0.84
12,13,328,112,4,4.0,4.5,9.10,1,0.78
13,14,307,109,3,4.0,3.0,8.00,1,0.62
14,15,311,104,3,3.5,2.0,8.20,1,0.61
15,16,314,105,3,3.5,2.5,8.30,0,0.54
16,17,317,107,3,4.0,3.0,8.70,0,0.66
17,18,319,106,3,4.0,3.0,8.00,1,0.65
18,19,318,110,3,4.0,3.0,8.80,0,0.63
19,20,303,102,3,3.5,3.0,8.50,0,0.62

Before beginning to work with this dataset and evaluating graduate admissions data, we will verify that there is no missing data in the dataset. Do this in the cell below.

In [5]:
# your code here
null_cols = data.isnull().sum()
null_cols
#no missing values in the dataset

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

Interestingly, there is a column that uniquely identifies the applicants. This column is the serial number column. Instead of having our own index, we should make this column our index. Do this in the cell below. Keep the column in the dataframe in addition to making it an index.

In [6]:
# your code here
data=data.set_index("Serial No.",drop=False)
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,,
1,1,337,118,4,4.5,4.5,9.65,1,0.92
2,2,324,107,4,4.0,4.5,8.87,1,0.76
3,3,316,104,3,3.0,3.5,8.00,1,0.72
4,4,322,110,3,3.5,2.5,8.67,1,0.80
5,5,314,103,2,2.0,3.0,8.21,0,0.65

Turns out that `GRE Score` and `CGPA` also uniquely identify the data. Show this in the cell below.

In [7]:
# your code here
#1.try
#data.groupby(["GRE Score","CGPA"]).sum.
#2.
test=data[["GRE Score","CGPA"]]
test.shape
test.drop_duplicates
test.shape
#There were no dupplicates so those 2 rows  together to identify the data

(400, 2)

Replace the index with an index comprised of two columns - `GRE Score` and `CGPA`. Remove the columns from the dataset as well. Make sure to use `inplace=True`.

Now change the index back to a sequence starting at zero using the `reset_index` function. Make sure to use `inplace=True`.

In [8]:
# your code here
data.head()
data=data.set_index(["GRE Score", "CGPA"])
data.reset_index()

,GRE Score,CGPA,Serial No.,TOEFL Score,University Rating,SOP,LOR,Research,Chance of Admit
0,337,9.65,1,118,4,4.5,4.5,1,0.92
1,324,8.87,2,107,4,4.0,4.5,1,0.76
2,316,8.00,3,104,3,3.0,3.5,1,0.72
3,322,8.67,4,110,3,3.5,2.5,1,0.80
4,314,8.21,5,103,2,2.0,3.0,0,0.65
5,330,9.34,6,115,5,4.5,3.0,1,0.90
6,321,8.20,7,109,3,3.0,4.0,1,0.75
7,308,7.90,8,101,2,3.0,4.0,0,0.68
8,302,8.00,9,102,1,2.0,1.5,0,0.50
9,323,8.60,10,108,3,3.5,3.0,0,0.45
10,325,8.40,11,106,3,3.5,4.0,1,0.52
11,327,9.00,12,111,4,4.0,4.5,1,0.84
12,328,9.10,13,112,4,4.0,4.5,1,0.78
13,307,8.00,14,109,3,4.0,3.0,1,0.62
14,311,8.20,15,104,3,3.5,2.0,1,0.61
15,314,8.30,16,105,3,3.5,2.5,0,0.54
16,317,8.70,17,107,3,4.0,3.0,0,0.66
17,319,8.00,18,106,3,4.0,3.0,1,0.65
18,318,8.80,19,110,3,4.0,3.0,0,0.63
19,303,8.50,20,102,3,3.5,3.0,0,0.62
20,312,7.90,21,107,3,3.0,2.0,1,0.64
21,325,8.40,22,114,4,3.0,2.0,0,0.70
22,328,9.50,23,116,5,5.0,5.0,1,0.94
23,334,9.70,24,119,5,5.0,4.5,1,0.95
24,336,9.80,25,119,5,4.0,3.5,1,0.97
25,340,9.60,26,120,5,4.5,4.5,1,0.94
26,322,8.80,27,109,5,4.5,3.5,0,0.76
27,298,7.50,28,98,2,1.5,2.5,1,0.44
28,295,7.20,29,93,1,2.0,2.0,0,0.46
29,310,7.30,30,99,2,1.5,2.0,0,0.54
...,...,...,...,...,...,...,...,...,...
370,310,8.24,371,103,2,2.5,2.5,0,0.72
371,324,9.22,372,110,3,3.5,3.0,1,0.89
372,336,9.62,373,119,4,4.5,4.0,1,0.95
373,321,8.54,374,109,3,3.0,3.0,1,0.79
374,315,7.65,375,105,2,2.0,2.5,0,0.39
375,304,7.66,376,101,2,2.0,2.5,0,0.38
376,297,7.43,377,96,2,2.5,2.0,0,0.34
377,290,7.56,378,100,1,1.5,2.0,0,0.47
378,303,7.65,379,98,1,2.0,2.5,0,0.56
379,311,8.43,380,99,1,2.5,3.0,1,0.71
380,322,8.84,381,104,3,3.5,4.0,1,0.78
381,319,8.67,382,105,3,3.0,3.5,1,0.73
382,324,9.15,383,110,4,4.5,4.0,1,0.82
383,300,8.26,384,100,3,3.0,3.5,0,0.62
384,340,9.74,385,113,4,5.0,5.0,1,0.96
385,335,9.82,386,117,5,5.0,5.0,1,0.96
386,302,7.96,387,101,2,2.5,3.5,0,0.46
387,307,8.10,388,105,2,2.0,3.5,0,0.53
388,296,7.80,389,97,2,1.5,2.0,0,0.49
389,320,8.44,390,108,3,3.5,4.0,1,0.76
390,314,8.24,391,102,2,2.0,2.5,0,0.64
391,318,8.65,392,106,3,2.0,3.0,0,0.71
392,326,9.12,393,112,4,4.0,3.5,1,0.84
393,317,8.76,394,104,2,3.0,3.0,0,0.77
394,329,9.23,395,111,4,4.5,4.0,1,0.89
395,324,9.04,396,110,3,3.5,3.5,1,0.82
396,325,9.11,397,107,3,3.0,3.5,1,0.84
397,330,9.45,398,116,4,5.0,4.5,1,0.91
398,312,8.78,399,103,3,3.5,4.0,0,0.67
399,333,9.66,400,117,4,5.0,4.0,1,0.95

# Challenge 2 - Advanced Functions

In this part of the lab, we would like to test complex conditions on the entire dataset at once. Let's start by finding the number of rows where the CGPA is higher than 9 and the student has conducted research.

In [11]:
# your code here
data.head()
data.loc[(data["CGPA"]>9) & (data["Research"]==1)]
data.CGPA.apply(np.mean)

0      9.65
1      8.87
2      8.00
3      8.67
4      8.21
5      9.34
6      8.20
7      7.90
8      8.00
9      8.60
10     8.40
11     9.00
12     9.10
13     8.00
14     8.20
15     8.30
16     8.70
17     8.00
18     8.80
19     8.50
20     7.90
21     8.40
22     9.50
23     9.70
24     9.80
25     9.60
26     8.80
27     7.50
28     7.20
29     7.30
       ...
370    8.24
371    9.22
372    9.62
373    8.54
374    7.65
375    7.66
376    7.43
377    7.56
378    7.65
379    8.43
380    8.84
381    8.67
382    9.15
383    8.26
384    9.74
385    9.82
386    7.96
387    8.10
388    7.80
389    8.44
390    8.24
391    8.65
392    9.12
393    8.76
394    9.23
395    9.04
396    9.11
397    9.45
398    8.78
399    9.66
Name: CGPA, Length: 400, dtype: float64

Now return all the rows where the CGPA is greater than 9 and the SOP score is less than 3.5. Find the mean chance of admit for these applicants.

In [12]:
# your code here
data.loc[(data["CGPA"]>9) & (data["SOP"]<3.5)].mean()

Serial No.           175.000
GRE Score            328.000
TOEFL Score          112.800
University Rating      3.400
SOP                    3.000
LOR                    3.400
CGPA                   9.130
Research               0.800
Chance of Admit        0.802
dtype: float64

We would like to create a deciding factor column for each student. We standardize several columns and then pick the most important factor from a lookup table. If the standardized value is above 0.8, the student will be accepted.

We will start by creating a standardized column for `CGPA`, `GRE Score` and `LOR`. We will name these columns `CGPA_std`, `GRE_std`, and `LOR_std` respecively.

Recall that standardizing a column is done by subtracting the mean of the column from all observations in the column and then dividing each observation in the column by the column's standard deviation.

In the cell below, write a standardization function (a function that takes a column as input and returns a standardized column as output). Make sure to use the `numpy` versions of mean and standard deviation.

In [13]:
def standardize(col):
    mean=col.apply(np.mean)
    std=col.apply(np.std)
    res= (col-mean)/std
    return res
    
    
    """
    This function takes a column from a dataframe 
    and returns a standardized column by subtracting the column's mean
    and dividing by the column's standard deviation.
    """
    
    # your code here

Now create the standardized columns `CGPA_std`, `GRE_std`, and `LOR_std` and add them to the `admissions` dataframe.

In [41]:
# your code here
#Usings assign could ve used insert as well
data2=data2.assign(CGPA_std=np.nan, GRE_std=np.nan, LOR_std=np.nan)
data2.head()
data2["CGPA_std"]=standardize(data2[["CGPA"]])
data2
data2["GRE_std"]=standardize(data2[["GRE Score"]])
data2
data2["LOR_std"]=standardize(data2[["LOR "]])
data2

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,decision,CGPA_std,GRE_std,LOR_std
0,1,337,118,4,4.5,4.5,9.65,1,0.92,NaN,1.764818,1.762107,1.167321
1,2,324,107,4,4.0,4.5,8.87,1,0.76,NaN,0.455151,0.627656,1.167321
2,3,316,104,3,3.0,3.5,8.00,1,0.72,NaN,-1.005631,-0.070467,0.052933
3,4,322,110,3,3.5,2.5,8.67,1,0.80,NaN,0.119339,0.453126,-1.061454
4,5,314,103,2,2.0,3.0,8.21,0,0.65,NaN,-0.653029,-0.244998,-0.504260
5,6,330,115,5,4.5,3.0,9.34,1,0.90,NaN,1.244310,1.151249,-0.504260
6,7,321,109,3,3.0,4.0,8.20,1,0.75,NaN,-0.669819,0.365860,0.610127
7,8,308,101,2,3.0,4.0,7.90,0,0.68,NaN,-1.173537,-0.768590,0.610127
8,9,302,102,1,2.0,1.5,8.00,0,0.50,NaN,-1.005631,-1.292182,-2.175842
9,10,323,108,3,3.5,3.0,8.60,0,0.45,NaN,0.001805,0.540391,-0.504260
10,11,325,106,3,3.5,4.0,8.40,1,0.52,NaN,-0.334007,0.714922,0.610127
11,12,327,111,4,4.0,4.5,9.00,1,0.84,NaN,0.673429,0.889453,1.167321
12,13,328,112,4,4.0,4.5,9.10,1,0.78,NaN,0.841335,0.976718,1.167321
13,14,307,109,3,4.0,3.0,8.00,1,0.62,NaN,-1.005631,-0.855855,-0.504260
14,15,311,104,3,3.5,2.0,8.20,1,0.61,NaN,-0.669819,-0.506794,-1.618648
15,16,314,105,3,3.5,2.5,8.30,0,0.54,NaN,-0.501913,-0.244998,-1.061454
16,17,317,107,3,4.0,3.0,8.70,0,0.66,NaN,0.169711,0.016799,-0.504260
17,18,319,106,3,4.0,3.0,8.00,1,0.65,NaN,-1.005631,0.191329,-0.504260
18,19,318,110,3,4.0,3.0,8.80,0,0.63,NaN,0.337617,0.104064,-0.504260
19,20,303,102,3,3.5,3.0,8.50,0,0.62,NaN,-0.166101,-1.204917,-0.504260
20,21,312,107,3,3.0,2.0,7.90,1,0.64,NaN,-1.173537,-0.419528,-1.618648
21,22,325,114,4,3.0,2.0,8.40,0,0.70,NaN,-0.334007,0.714922,-1.618648
22,23,328,116,5,5.0,5.0,9.50,1,0.94,NaN,1.512959,0.976718,1.724515
23,24,334,119,5,5.0,4.5,9.70,1,0.95,NaN,1.848771,1.500310,1.167321
24,25,336,119,5,4.0,3.5,9.80,1,0.97,NaN,2.016677,1.674841,0.052933
25,26,340,120,5,4.5,4.5,9.60,1,0.94,NaN,1.680865,2.023903,1.167321
26,27,322,109,5,4.5,3.5,8.80,0,0.76,NaN,0.337617,0.453126,0.052933
27,28,298,98,2,1.5,2.5,7.50,1,0.44,NaN,-1.845161,-1.641244,-1.061454
28,29,295,93,1,2.0,2.0,7.20,0,0.46,NaN,-2.348879,-1.903040,-1.618648
29,30,310,99,2,1.5,2.0,7.30,0,0.54,NaN,-2.180973,-0.594059,-1.618648
...,...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,310,103,2,2.5,2.5,8.24,0,0.72,NaN,-0.602657,-0.594059,-1.061454
371,372,324,110,3,3.5,3.0,9.22,1,0.89,NaN,1.042822,0.627656,-0.504260
372,373,336,119,4,4.5,4.0,9.62,1,0.95,NaN,1.714446,1.674841,0.610127
373,374,321,109,3,3.0,3.0,8.54,1,0.79,NaN,-0.098939,0.365860,-0.504260
374,375,315,105,2,2.0,2.5,7.65,0,0.39,NaN,-1.593302,-0.157732,-1.061454
375,376,304,101,2,2.0,2.5,7.66,0,0.38,NaN,-1.576512,-1.117652,-1.061454
376,377,297,96,2,2.5,2.0,7.43,0,0.34,NaN,-1.962696,-1.728509,-1.618648
377,378,290,100,1,1.5,2.0,7.56,0,0.47,NaN,-1.744418,-2.339367,-1.618648
378,379,303,98,1,2.0,2.5,7.65,0,0.56,NaN,-1.593302,-1.204917,-1.061454
379,380,311,99,1,2.5,3.0,8.43,1,0.71,NaN,-0.283635,-0.506794,-0.504260
380,381,322,104,3,3.5,4.0,8.84,1,0.78,NaN,0.404779,0.453126,0.610127
381,382,319,105,3,3.0,3.5,8.67,1,0.73,NaN,0.119339,0.191329,0.052933
382,383,324,110,4,4.5,4.0,9.15,1,0.82,NaN,0.925288,0.627656,0.610127
383,384,300,100,3,3.0,3.5,8.26,0,0.62,NaN,-0.569076,-1.466713,0.052933
384,385,340,113,4,5.0,5.0,9.74,1,0.96,NaN,1.915934,2.023903,1.724515
385,386,335,117,5,5.0,5.0,9.82,1,0.96,NaN,2.050259,1.587576,1.724515
386,387,302,101,2,2.5,3.5,7.96,0,0.46,NaN,-1.072794,-1.292182,0.052933
387,388,307,105,2,2.0,3.5,8.10,0,0.53,NaN,-0.837725,-0.855855,0.052933
388,389,296,97,2,1.5,2.0,7.80,0,0.49,NaN,-1.341443,-1.815775,-1.618648
389,390,320,108,3,3.5,4.0,8.44,1,0.76,NaN,-0.266845,0.278595,0.610127
390,391,314,102,2,2.0,2.5,8.24,0,0.64,NaN,-0.602657,-0.244998,-1.061454
391,392,318,106,3,2.0,3.0,8.65,0,0.71,NaN,0.085758,0.104064,-0.504260
392,393,326,112,4,4.0,3.5,9.12,1,0.84,NaN,0.874916,0.802187,0.052933
393,394,317,104,2,3.0,3.0,8.76,0,0.77,NaN,0.270455,0.016799,-0.504260
394,395,329,111,4,4.5,4.0,9.23,1,0.89,NaN,1.059613,1.063983,0.610127
395,396,324,110,3,3.5,3.5,9.04,1,0.82,NaN,0.740592,0.627656,0.052933
396,397,325,107,3,3.0,3.5,9.11,1,0.84,NaN,0.858126,0.714922,0.052933
397,398,330,116,4,5.0,4.5,9.45,1,0.91,NaN,1.429006,1.151249,1.167321
398,399,312,103,3,3.5,4.0,8.78,0,0.67,NaN,0.304036,-0.419528,0.610127
399,400,333,117,4,5.0,4.0,9.66,1,0.95,NaN,1.781609,1.413045,0.610127

We will generate the decision choice at random using the code below. Please run the cell.

In [15]:
# Libraries
from random import choices

In [42]:
std_columns = ['CGPA_std', 'GRE_std', 'LOR_std']

decision_choice = choices(std_columns, k=data2.shape[0])
data2.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit ', 'decision', 'CGPA_std',
       'GRE_std', 'LOR_std'],
      dtype='object')

Now create the deciding column using the `lookup` function. The lookup column is `decision_choice` found above. Call the column resulting from the lookup function `deciding_column` and add it to the `admissions` dataframe.

In [43]:
# your code here
#data2=data.assign(deciding_column=np.nan)
data2
data2["deciding_column"]=data2.lookup(data2.index, decision_choice)

Create a column called `decision` in the `admissions` dataframe. Assign 1 to this column if the value of `deciding_column` is greater than 0.8 and 0 otherwise.

In [49]:
# your code here
data2=data2.assign(decision=np.nan)
data2.head(29)
data2["decision"]=np.where(data2["deciding_column"]>0.8,1,0)
data2.head(30)

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit,decision,CGPA_std,GRE_std,LOR_std,deciding_column
0,1,337,118,4,4.5,4.5,9.65,1,0.92,1,1.764818,1.762107,1.167321,1.762107
1,2,324,107,4,4.0,4.5,8.87,1,0.76,0,0.455151,0.627656,1.167321,0.455151
2,3,316,104,3,3.0,3.5,8.00,1,0.72,0,-1.005631,-0.070467,0.052933,-1.005631
3,4,322,110,3,3.5,2.5,8.67,1,0.80,0,0.119339,0.453126,-1.061454,-1.061454
4,5,314,103,2,2.0,3.0,8.21,0,0.65,0,-0.653029,-0.244998,-0.504260,-0.653029
5,6,330,115,5,4.5,3.0,9.34,1,0.90,0,1.244310,1.151249,-0.504260,-0.504260
6,7,321,109,3,3.0,4.0,8.20,1,0.75,0,-0.669819,0.365860,0.610127,0.610127
7,8,308,101,2,3.0,4.0,7.90,0,0.68,0,-1.173537,-0.768590,0.610127,-1.173537
8,9,302,102,1,2.0,1.5,8.00,0,0.50,0,-1.005631,-1.292182,-2.175842,-1.292182
9,10,323,108,3,3.5,3.0,8.60,0,0.45,0,0.001805,0.540391,-0.504260,-0.504260
10,11,325,106,3,3.5,4.0,8.40,1,0.52,0,-0.334007,0.714922,0.610127,-0.334007
11,12,327,111,4,4.0,4.5,9.00,1,0.84,0,0.673429,0.889453,1.167321,0.673429
12,13,328,112,4,4.0,4.5,9.10,1,0.78,1,0.841335,0.976718,1.167321,0.841335
13,14,307,109,3,4.0,3.0,8.00,1,0.62,0,-1.005631,-0.855855,-0.504260,-0.855855
14,15,311,104,3,3.5,2.0,8.20,1,0.61,0,-0.669819,-0.506794,-1.618648,-1.618648
15,16,314,105,3,3.5,2.5,8.30,0,0.54,0,-0.501913,-0.244998,-1.061454,-0.501913
16,17,317,107,3,4.0,3.0,8.70,0,0.66,0,0.169711,0.016799,-0.504260,0.169711
17,18,319,106,3,4.0,3.0,8.00,1,0.65,0,-1.005631,0.191329,-0.504260,-0.504260
18,19,318,110,3,4.0,3.0,8.80,0,0.63,0,0.337617,0.104064,-0.504260,-0.504260
19,20,303,102,3,3.5,3.0,8.50,0,0.62,0,-0.166101,-1.204917,-0.504260,-0.504260
20,21,312,107,3,3.0,2.0,7.90,1,0.64,0,-1.173537,-0.419528,-1.618648,-1.173537
21,22,325,114,4,3.0,2.0,8.40,0,0.70,0,-0.334007,0.714922,-1.618648,-0.334007
22,23,328,116,5,5.0,5.0,9.50,1,0.94,1,1.512959,0.976718,1.724515,1.724515
23,24,334,119,5,5.0,4.5,9.70,1,0.95,1,1.848771,1.500310,1.167321,1.500310
24,25,336,119,5,4.0,3.5,9.80,1,0.97,0,2.016677,1.674841,0.052933,0.052933
25,26,340,120,5,4.5,4.5,9.60,1,0.94,1,1.680865,2.023903,1.167321,1.167321
26,27,322,109,5,4.5,3.5,8.80,0,0.76,0,0.337617,0.453126,0.052933,0.337617
27,28,298,98,2,1.5,2.5,7.50,1,0.44,0,-1.845161,-1.641244,-1.061454,-1.641244
28,29,295,93,1,2.0,2.0,7.20,0,0.46,0,-2.348879,-1.903040,-1.618648,-1.903040
29,30,310,99,2,1.5,2.0,7.30,0,0.54,0,-2.180973,-0.594059,-1.618648,-1.618648

How many applicants will be accepted to the program using the decision column? Compute the result below.

In [56]:
# your code here
#data2.loc(data2["decision"]==1)
res=data2.loc[data2['decision'] == 1].shape
print(res[0],"students get in")

86 students get in

# Challenge 3 - Method Chaining

To increase our coding efficiency, let's make a number of changes to our dataframe in one line of code.

In the cell below, remove all non character symbols from the column names, replace all spaces in column names to underscores, and change all upper case characters to lower case. Assign these new column values to `admissions.columns`.

In [85]:
# your code here
admissions=pd.read_csv("Admission_Predict.csv")
admissions.columns=admissions.columns.str.strip().str.lower().str.replace(" ", "_")
#admissions.columns
admissions.head()

,serial_no.,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,chance_of_admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In the cell below, give all student with a university rating of 4 or higher a 10 point boost on their GRE score and split the column into 4 bins using the `cut` function. Assign this new score to the variable `adjusted_gre`.

In [86]:
# your code here

admissions["gre_score"]=np.where(admissions["university_rating"]>=4,admissions["gre_score"]+10,admissions["gre_score"]+0)
admissions["adjusted_gre"]=pd.cut(admissions.gre_score,bins=[280,300,320,340,360],labels=["Worst","Medium","Good","Best"])
admissions.head(60)

,serial_no.,gre_score,toefl_score,university_rating,sop,lor,cgpa,research,chance_of_admit,adjusted_gre
0,1,347,118,4,4.5,4.5,9.65,1,0.92,Best
1,2,334,107,4,4.0,4.5,8.87,1,0.76,Good
2,3,316,104,3,3.0,3.5,8.00,1,0.72,Medium
3,4,322,110,3,3.5,2.5,8.67,1,0.80,Good
4,5,314,103,2,2.0,3.0,8.21,0,0.65,Medium
5,6,340,115,5,4.5,3.0,9.34,1,0.90,Good
6,7,321,109,3,3.0,4.0,8.20,1,0.75,Good
7,8,308,101,2,3.0,4.0,7.90,0,0.68,Medium
8,9,302,102,1,2.0,1.5,8.00,0,0.50,Medium
9,10,323,108,3,3.5,3.0,8.60,0,0.45,Good
10,11,325,106,3,3.5,4.0,8.40,1,0.52,Good
11,12,337,111,4,4.0,4.5,9.00,1,0.84,Good
12,13,338,112,4,4.0,4.5,9.10,1,0.78,Good
13,14,307,109,3,4.0,3.0,8.00,1,0.62,Medium
14,15,311,104,3,3.5,2.0,8.20,1,0.61,Medium
15,16,314,105,3,3.5,2.5,8.30,0,0.54,Medium
16,17,317,107,3,4.0,3.0,8.70,0,0.66,Medium
17,18,319,106,3,4.0,3.0,8.00,1,0.65,Medium
18,19,318,110,3,4.0,3.0,8.80,0,0.63,Medium
19,20,303,102,3,3.5,3.0,8.50,0,0.62,Medium
20,21,312,107,3,3.0,2.0,7.90,1,0.64,Medium
21,22,335,114,4,3.0,2.0,8.40,0,0.70,Good
22,23,338,116,5,5.0,5.0,9.50,1,0.94,Good
23,24,344,119,5,5.0,4.5,9.70,1,0.95,Best
24,25,346,119,5,4.0,3.5,9.80,1,0.97,Best
25,26,350,120,5,4.5,4.5,9.60,1,0.94,Best
26,27,332,109,5,4.5,3.5,8.80,0,0.76,Good
27,28,298,98,2,1.5,2.5,7.50,1,0.44,Worst
28,29,295,93,1,2.0,2.0,7.20,0,0.46,Worst
29,30,310,99,2,1.5,2.0,7.30,0,0.54,Medium
30,31,300,97,2,3.0,3.0,8.10,1,0.65,Worst
31,32,327,103,3,4.0,4.0,8.30,1,0.74,Good
32,33,348,118,4,3.0,4.5,9.40,1,0.91,Best
33,34,350,114,5,4.0,4.0,9.60,1,0.90,Best
34,35,341,112,5,4.0,5.0,9.80,1,0.94,Best
35,36,330,110,5,5.0,5.0,9.20,1,0.88,Good
36,37,299,106,2,4.0,4.0,8.40,0,0.64,Worst
37,38,300,105,1,1.0,2.0,7.80,0,0.58,Worst
38,39,304,105,1,3.0,1.5,7.50,0,0.52,Medium
39,40,307,108,2,4.0,3.5,7.70,0,0.48,Medium
40,41,308,110,3,3.5,3.0,8.00,1,0.46,Medium
41,42,316,105,2,2.5,2.5,8.20,1,0.49,Medium
42,43,313,107,2,2.5,2.0,8.50,1,0.53,Medium
43,44,342,117,4,4.5,4.0,9.10,0,0.87,Best
44,45,336,113,5,4.5,4.0,9.40,1,0.91,Good
45,46,332,110,5,5.0,4.0,9.10,1,0.88,Good
46,47,339,114,5,4.0,5.0,9.30,1,0.86,Good
47,48,349,119,5,4.5,4.0,9.70,0,0.89,Best
48,49,321,110,3,3.5,5.0,8.85,1,0.82,Good
49,50,337,111,4,3.0,4.0,8.40,1,0.78,Good
50,51,313,98,3,2.5,4.5,8.30,1,0.76,Medium
51,52,312,100,2,1.5,3.5,7.90,1,0.56,Medium
52,53,344,116,4,4.0,3.0,8.00,1,0.78,Best
53,54,334,112,4,4.0,2.5,8.10,1,0.72,Good
54,55,322,110,3,3.0,3.5,8.00,0,0.70,Good
55,56,320,103,3,3.0,3.0,7.70,0,0.64,Medium
56,57,316,102,3,2.0,3.0,7.40,0,0.64,Medium
57,58,298,99,2,4.0,2.0,7.60,0,0.46,Worst
58,59,300,99,1,3.0,2.0,6.80,1,0.36,Worst
59,60,311,104,2,2.0,2.0,8.30,0,0.42,Medium